### ISSUE TITLE
Bug: All your placehold.it links seem to be broken

### ISSUE THREAD

**Issue by joshgoebel** [tinted-theming/base24#17]
Possibly be because the url has changed to https://placeholder.com/?

![Snap_2022-07-04_471x476](https://user-images.githubusercontent.com/6473/177229417-61dba283-ecd2-42ae-bee2-163cfa7fe67c.png)

**Comment by joshgoebel** [comment]
Is SVGs will do it that sounds most feature proof - is gitHub allows them.

**Comment by FredHappyface** [comment]
Not in the way I'd like. eg. directly in the readme
