### ISSUE TITLE
placehold.it colors preview is broken

### ISSUE THREAD

**Issue by NNBnh** [tinted-theming/base24#19]
On https://github.com/tinted-theming/base24/blob/master/styling.md:

![image](https://user-images.githubusercontent.com/43980777/214020884-14ff39cb-4913-4da4-b180-c19b97d6a76a.png)

**Comment by FredHappyface** [comment]
Hi, cheers for the issue

Did you take a look at closed issues? Looks like there was one at https://github.com/tinted-theming/base24/issues/17. Unfortunately there's no nice way to add colours to markdown so gonna mark this won't do
