### ISSUE TITLE
color_wheel.png in README.md missing

### ISSUE THREAD

**Issue by clach04** [tinted-theming/base24#23]
https://github.com/tinted-theming/base24/blob/aca3ec337333337dab257cfca05c880f1188f64f/README.md?plain=1#L2

Introduced in  commit b95aae1e4dfcc79c83cd553750baf8fc8f7c0deb (HEAD) by @FredHappyface  on     Date:   Sat Oct 22 02:11:38 2022 +0100

@FredHappyface do you still have this on your machine to commit/submit?

**Comment by FredHappyface** [comment]
Cheers sorted this in https://github.com/tinted-theming/base24/pull/24 :)
