### ISSUE TITLE
Why is `base0F` deprecated?

### ISSUE THREAD

**Issue by musjj** [tinted-theming/base24#27]
https://github.com/tinted-theming/base24/blob/18af13d81e31a37be3617891c0a9e7a87da0ade9/styling.md?plain=1#L56

Is there a reason why the color is deprecated? It seems like a waste to remove a color from the already scarce 24-slot bandwidth. Also this means that there are actually only 23 colors, making the name misleading.

**Comment by FredHappyface** [comment]
This was originally due to a misunderstanding with the base16 documentation. So I really need to update the documentation. Essentially, it's not actually deprecated at all, and was intended as a colour for deprecated functions etc

**Comment by FredHappyface** [comment]
Updated in https://github.com/tinted-theming/base24/commit/cdb598c5b2a0bdba52269aaaa82c9ce41a50d890
